// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health messages
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Hostname            string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	UptimeSeconds       int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	AvailableInterfaces []string               `protobuf:"bytes,4,rep,name=available_interfaces,json=availableInterfaces,proto3" json:"available_interfaces,omitempty"`
	BypassConfEnabled   bool                   `protobuf:"varint,5,opt,name=bypass_conf_enabled,json=bypassConfEnabled,proto3" json:"bypass_conf_enabled,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetAvailableInterfaces() []string {
	if x != nil {
		return x.AvailableInterfaces
	}
	return nil
}

func (x *HealthResponse) GetBypassConfEnabled() bool {
	if x != nil {
		return x.BypassConfEnabled
	}
	return false
}

// Show messages - equivalent to `wg show <interface> dump`
type ShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowRequest) Reset() {
	*x = ShowRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowRequest) ProtoMessage() {}

func (x *ShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowRequest.ProtoReflect.Descriptor instead.
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ShowRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type ShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ListenPort    int32                  `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	Fwmark        int64                  `protobuf:"varint,3,opt,name=fwmark,proto3" json:"fwmark,omitempty"`
	Peers         []*PeerStatus          `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowResponse) Reset() {
	*x = ShowResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowResponse) ProtoMessage() {}

func (x *ShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowResponse.ProtoReflect.Descriptor instead.
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ShowResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ShowResponse) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *ShowResponse) GetFwmark() int64 {
	if x != nil {
		return x.Fwmark
	}
	return 0
}

func (x *ShowResponse) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PresharedKeySet     string                 `protobuf:"bytes,2,opt,name=preshared_key_set,json=presharedKeySet,proto3" json:"preshared_key_set,omitempty"` // "true" or "false" or "(none)"
	Endpoint            string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,4,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	LatestHandshakeUnix int64                  `protobuf:"varint,5,opt,name=latest_handshake_unix,json=latestHandshakeUnix,proto3" json:"latest_handshake_unix,omitempty"`
	TransferRx          int64                  `protobuf:"varint,6,opt,name=transfer_rx,json=transferRx,proto3" json:"transfer_rx,omitempty"`
	TransferTx          int64                  `protobuf:"varint,7,opt,name=transfer_tx,json=transferTx,proto3" json:"transfer_tx,omitempty"`
	PersistentKeepalive int32                  `protobuf:"varint,8,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_api_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PeerStatus) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerStatus) GetPresharedKeySet() string {
	if x != nil {
		return x.PresharedKeySet
	}
	return ""
}

func (x *PeerStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerStatus) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PeerStatus) GetLatestHandshakeUnix() int64 {
	if x != nil {
		return x.LatestHandshakeUnix
	}
	return 0
}

func (x *PeerStatus) GetTransferRx() int64 {
	if x != nil {
		return x.TransferRx
	}
	return 0
}

func (x *PeerStatus) GetTransferTx() int64 {
	if x != nil {
		return x.TransferTx
	}
	return 0
}

func (x *PeerStatus) GetPersistentKeepalive() int32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

// SyncConf messages - equivalent to `wg syncconf <interface> <config>`
type SyncConfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	ConfigContent []byte                 `protobuf:"bytes,2,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"` // Stripped config content (without Interface section)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncConfRequest) Reset() {
	*x = SyncConfRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfRequest) ProtoMessage() {}

func (x *SyncConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfRequest.ProtoReflect.Descriptor instead.
func (*SyncConfRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SyncConfRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *SyncConfRequest) GetConfigContent() []byte {
	if x != nil {
		return x.ConfigContent
	}
	return nil
}

type SyncConfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncConfResponse) Reset() {
	*x = SyncConfResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfResponse) ProtoMessage() {}

func (x *SyncConfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfResponse.ProtoReflect.Descriptor instead.
func (*SyncConfResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SyncConfResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncConfResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SetPeer messages - equivalent to `wg set <interface> peer <pubkey> ...`
type SetPeerRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName       string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	PublicKey           string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Endpoint            *string                `protobuf:"bytes,4,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	PersistentKeepalive *int32                 `protobuf:"varint,5,opt,name=persistent_keepalive,json=persistentKeepalive,proto3,oneof" json:"persistent_keepalive,omitempty"`
	PresharedKey        *string                `protobuf:"bytes,6,opt,name=preshared_key,json=presharedKey,proto3,oneof" json:"preshared_key,omitempty"`
	RemovePresharedKey  bool                   `protobuf:"varint,7,opt,name=remove_preshared_key,json=removePresharedKey,proto3" json:"remove_preshared_key,omitempty"` // Set to true to remove PSK
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetPeerRequest) Reset() {
	*x = SetPeerRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerRequest) ProtoMessage() {}

func (x *SetPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerRequest.ProtoReflect.Descriptor instead.
func (*SetPeerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SetPeerRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *SetPeerRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SetPeerRequest) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *SetPeerRequest) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *SetPeerRequest) GetPersistentKeepalive() int32 {
	if x != nil && x.PersistentKeepalive != nil {
		return *x.PersistentKeepalive
	}
	return 0
}

func (x *SetPeerRequest) GetPresharedKey() string {
	if x != nil && x.PresharedKey != nil {
		return *x.PresharedKey
	}
	return ""
}

func (x *SetPeerRequest) GetRemovePresharedKey() bool {
	if x != nil {
		return x.RemovePresharedKey
	}
	return false
}

type SetPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeerResponse) Reset() {
	*x = SetPeerResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerResponse) ProtoMessage() {}

func (x *SetPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerResponse.ProtoReflect.Descriptor instead.
func (*SetPeerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SetPeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetPeerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RemovePeer messages - equivalent to `wg set <interface> peer <pubkey> remove`
type RemovePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerRequest) Reset() {
	*x = RemovePeerRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerRequest) ProtoMessage() {}

func (x *RemovePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerRequest.ProtoReflect.Descriptor instead.
func (*RemovePeerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RemovePeerRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *RemovePeerRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type RemovePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerResponse) Reset() {
	*x = RemovePeerResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerResponse) ProtoMessage() {}

func (x *RemovePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerResponse.ProtoReflect.Descriptor instead.
func (*RemovePeerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *RemovePeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemovePeerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GenPSK messages - equivalent to `wg genpsk`
type GenPSKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenPSKRequest) Reset() {
	*x = GenPSKRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenPSKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenPSKRequest) ProtoMessage() {}

func (x *GenPSKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenPSKRequest.ProtoReflect.Descriptor instead.
func (*GenPSKRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{11}
}

type GenPSKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PresharedKey  string                 `protobuf:"bytes,1,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenPSKResponse) Reset() {
	*x = GenPSKResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenPSKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenPSKResponse) ProtoMessage() {}

func (x *GenPSKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenPSKResponse.ProtoReflect.Descriptor instead.
func (*GenPSKResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *GenPSKResponse) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

// GenKeyPair messages - equivalent to `wg genkey` + `wg pubkey`
type GenKeyPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenKeyPairRequest) Reset() {
	*x = GenKeyPairRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenKeyPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenKeyPairRequest) ProtoMessage() {}

func (x *GenKeyPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenKeyPairRequest.ProtoReflect.Descriptor instead.
func (*GenKeyPairRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{13}
}

type GenKeyPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenKeyPairResponse) Reset() {
	*x = GenKeyPairResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenKeyPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenKeyPairResponse) ProtoMessage() {}

func (x *GenKeyPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenKeyPairResponse.ProtoReflect.Descriptor instead.
func (*GenKeyPairResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *GenKeyPairResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *GenKeyPairResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// ReadConfig messages - read WireGuard config file
type ReadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadConfigRequest) Reset() {
	*x = ReadConfigRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfigRequest) ProtoMessage() {}

func (x *ReadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReadConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ReadConfigRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type ReadConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Content        []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ModifiedAtUnix int64                  `protobuf:"varint,2,opt,name=modified_at_unix,json=modifiedAtUnix,proto3" json:"modified_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadConfigResponse) Reset() {
	*x = ReadConfigResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfigResponse) ProtoMessage() {}

func (x *ReadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReadConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ReadConfigResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReadConfigResponse) GetModifiedAtUnix() int64 {
	if x != nil {
		return x.ModifiedAtUnix
	}
	return 0
}

// WriteConfig messages - write WireGuard config file atomically
type WriteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreateBackup  bool                   `protobuf:"varint,3,opt,name=create_backup,json=createBackup,proto3" json:"create_backup,omitempty"` // Create backup before writing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteConfigRequest) Reset() {
	*x = WriteConfigRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfigRequest) ProtoMessage() {}

func (x *WriteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfigRequest.ProtoReflect.Descriptor instead.
func (*WriteConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *WriteConfigRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *WriteConfigRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteConfigRequest) GetCreateBackup() bool {
	if x != nil {
		return x.CreateBackup
	}
	return false
}

type WriteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	BackupName    string                 `protobuf:"bytes,3,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"` // Name of backup file if created
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteConfigResponse) Reset() {
	*x = WriteConfigResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfigResponse) ProtoMessage() {}

func (x *WriteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfigResponse.ProtoReflect.Descriptor instead.
func (*WriteConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *WriteConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WriteConfigResponse) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

// Backup messages
type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"` // Optional: filter by interface
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ListBackupsRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type BackupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InterfaceName string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,4,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupInfo) Reset() {
	*x = BackupInfo{}
	mi := &file_api_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupInfo) ProtoMessage() {}

func (x *BackupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupInfo.ProtoReflect.Descriptor instead.
func (*BackupInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *BackupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupInfo) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *BackupInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BackupInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type ListBackupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backups       []*BackupInfo          `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsResponse) Reset() {
	*x = ListBackupsResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResponse) ProtoMessage() {}

func (x *ListBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ListBackupsResponse) GetBackups() []*BackupInfo {
	if x != nil {
		return x.Backups
	}
	return nil
}

type CreateBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupRequest) Reset() {
	*x = CreateBackupRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupRequest) ProtoMessage() {}

func (x *CreateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{22}
}

func (x *CreateBackupRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type CreateBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Backup        *BackupInfo            `protobuf:"bytes,3,opt,name=backup,proto3" json:"backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupResponse) Reset() {
	*x = CreateBackupResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupResponse) ProtoMessage() {}

func (x *CreateBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupResponse.ProtoReflect.Descriptor instead.
func (*CreateBackupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{23}
}

func (x *CreateBackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBackupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateBackupResponse) GetBackup() *BackupInfo {
	if x != nil {
		return x.Backup
	}
	return nil
}

type GetBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupRequest) Reset() {
	*x = GetBackupRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupRequest) ProtoMessage() {}

func (x *GetBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupRequest.ProtoReflect.Descriptor instead.
func (*GetBackupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{24}
}

func (x *GetBackupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BackupChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupChunk) Reset() {
	*x = BackupChunk{}
	mi := &file_api_proto_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChunk) ProtoMessage() {}

func (x *BackupChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChunk.ProtoReflect.Descriptor instead.
func (*BackupChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{25}
}

func (x *BackupChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RestoreBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InterfaceName string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupRequest) Reset() {
	*x = RestoreBackupRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupRequest) ProtoMessage() {}

func (x *RestoreBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupRequest.ProtoReflect.Descriptor instead.
func (*RestoreBackupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{26}
}

func (x *RestoreBackupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestoreBackupRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type RestoreBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupResponse) Reset() {
	*x = RestoreBackupResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupResponse) ProtoMessage() {}

func (x *RestoreBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupResponse.ProtoReflect.Descriptor instead.
func (*RestoreBackupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{27}
}

func (x *RestoreBackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreBackupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupRequest) Reset() {
	*x = DeleteBackupRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupRequest) ProtoMessage() {}

func (x *DeleteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteBackupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupResponse) Reset() {
	*x = DeleteBackupResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupResponse) ProtoMessage() {}

func (x *DeleteBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupResponse.ProtoReflect.Descriptor instead.
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteBackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBackupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBypassConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBypassConfigRequest) Reset() {
	*x = GetBypassConfigRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBypassConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBypassConfigRequest) ProtoMessage() {}

func (x *GetBypassConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBypassConfigRequest.ProtoReflect.Descriptor instead.
func (*GetBypassConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{30}
}

type GetBypassConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"` // true if path is configured and file exists
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content        []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ModifiedAtUnix int64                  `protobuf:"varint,4,opt,name=modified_at_unix,json=modifiedAtUnix,proto3" json:"modified_at_unix,omitempty"`
	IpsetName      string                 `protobuf:"bytes,5,opt,name=ipset_name,json=ipsetName,proto3" json:"ipset_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBypassConfigResponse) Reset() {
	*x = GetBypassConfigResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBypassConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBypassConfigResponse) ProtoMessage() {}

func (x *GetBypassConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBypassConfigResponse.ProtoReflect.Descriptor instead.
func (*GetBypassConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{31}
}

func (x *GetBypassConfigResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetBypassConfigResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetBypassConfigResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetBypassConfigResponse) GetModifiedAtUnix() int64 {
	if x != nil {
		return x.ModifiedAtUnix
	}
	return 0
}

func (x *GetBypassConfigResponse) GetIpsetName() string {
	if x != nil {
		return x.IpsetName
	}
	return ""
}

type UpdateBypassConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	CreateBackup  bool                   `protobuf:"varint,2,opt,name=create_backup,json=createBackup,proto3" json:"create_backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBypassConfigRequest) Reset() {
	*x = UpdateBypassConfigRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBypassConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBypassConfigRequest) ProtoMessage() {}

func (x *UpdateBypassConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBypassConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateBypassConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateBypassConfigRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpdateBypassConfigRequest) GetCreateBackup() bool {
	if x != nil {
		return x.CreateBackup
	}
	return false
}

type UpdateBypassConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	RestartOutput string                 `protobuf:"bytes,3,opt,name=restart_output,json=restartOutput,proto3" json:"restart_output,omitempty"` // combined stdout/stderr of systemctl restart dnsmasq
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBypassConfigResponse) Reset() {
	*x = UpdateBypassConfigResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBypassConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBypassConfigResponse) ProtoMessage() {}

func (x *UpdateBypassConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBypassConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateBypassConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateBypassConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateBypassConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateBypassConfigResponse) GetRestartOutput() string {
	if x != nil {
		return x.RestartOutput
	}
	return ""
}

type ClearBypassIpsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBypassIpsetRequest) Reset() {
	*x = ClearBypassIpsetRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBypassIpsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBypassIpsetRequest) ProtoMessage() {}

func (x *ClearBypassIpsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBypassIpsetRequest.ProtoReflect.Descriptor instead.
func (*ClearBypassIpsetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{34}
}

type ClearBypassIpsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FlushOutput   string                 `protobuf:"bytes,3,opt,name=flush_output,json=flushOutput,proto3" json:"flush_output,omitempty"`       // output of `ipset flush <name>`
	RestartOutput string                 `protobuf:"bytes,4,opt,name=restart_output,json=restartOutput,proto3" json:"restart_output,omitempty"` // output of `systemctl restart dnsmasq`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBypassIpsetResponse) Reset() {
	*x = ClearBypassIpsetResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBypassIpsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBypassIpsetResponse) ProtoMessage() {}

func (x *ClearBypassIpsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBypassIpsetResponse.ProtoReflect.Descriptor instead.
func (*ClearBypassIpsetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{35}
}

func (x *ClearBypassIpsetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearBypassIpsetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ClearBypassIpsetResponse) GetFlushOutput() string {
	if x != nil {
		return x.FlushOutput
	}
	return ""
}

func (x *ClearBypassIpsetResponse) GetRestartOutput() string {
	if x != nil {
		return x.RestartOutput
	}
	return ""
}

var File_api_proto_agent_proto protoreflect.FileDescriptor

const file_api_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/agent.proto\x12\awgagent\"\x0f\n" +
	"\rHealthRequest\"\xd0\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x121\n" +
	"\x14available_interfaces\x18\x04 \x03(\tR\x13availableInterfaces\x12.\n" +
	"\x13bypass_conf_enabled\x18\x05 \x01(\bR\x11bypassConfEnabled\"4\n" +
	"\vShowRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\"\x91\x01\n" +
	"\fShowResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\x05R\n" +
	"listenPort\x12\x16\n" +
	"\x06fwmark\x18\x03 \x01(\x03R\x06fwmark\x12)\n" +
	"\x05peers\x18\x04 \x03(\v2\x13.wgagent.PeerStatusR\x05peers\"\xbd\x02\n" +
	"\n" +
	"PeerStatus\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12*\n" +
	"\x11preshared_key_set\x18\x02 \x01(\tR\x0fpresharedKeySet\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x03(\tR\n" +
	"allowedIps\x122\n" +
	"\x15latest_handshake_unix\x18\x05 \x01(\x03R\x13latestHandshakeUnix\x12\x1f\n" +
	"\vtransfer_rx\x18\x06 \x01(\x03R\n" +
	"transferRx\x12\x1f\n" +
	"\vtransfer_tx\x18\a \x01(\x03R\n" +
	"transferTx\x121\n" +
	"\x14persistent_keepalive\x18\b \x01(\x05R\x13persistentKeepalive\"_\n" +
	"\x0fSyncConfRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12%\n" +
	"\x0econfig_content\x18\x02 \x01(\fR\rconfigContent\"B\n" +
	"\x10SyncConfResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xe4\x02\n" +
	"\x0eSetPeerRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x12\x1f\n" +
	"\bendpoint\x18\x04 \x01(\tH\x00R\bendpoint\x88\x01\x01\x126\n" +
	"\x14persistent_keepalive\x18\x05 \x01(\x05H\x01R\x13persistentKeepalive\x88\x01\x01\x12(\n" +
	"\rpreshared_key\x18\x06 \x01(\tH\x02R\fpresharedKey\x88\x01\x01\x120\n" +
	"\x14remove_preshared_key\x18\a \x01(\bR\x12removePresharedKeyB\v\n" +
	"\t_endpointB\x17\n" +
	"\x15_persistent_keepaliveB\x10\n" +
	"\x0e_preshared_key\"A\n" +
	"\x0fSetPeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Y\n" +
	"\x11RemovePeerRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"D\n" +
	"\x12RemovePeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0f\n" +
	"\rGenPSKRequest\"5\n" +
	"\x0eGenPSKResponse\x12#\n" +
	"\rpreshared_key\x18\x01 \x01(\tR\fpresharedKey\"\x13\n" +
	"\x11GenKeyPairRequest\"T\n" +
	"\x12GenKeyPairResponse\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\":\n" +
	"\x11ReadConfigRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\"X\n" +
	"\x12ReadConfigResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12(\n" +
	"\x10modified_at_unix\x18\x02 \x01(\x03R\x0emodifiedAtUnix\"z\n" +
	"\x12WriteConfigRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12#\n" +
	"\rcreate_backup\x18\x03 \x01(\bR\fcreateBackup\"f\n" +
	"\x13WriteConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vbackup_name\x18\x03 \x01(\tR\n" +
	"backupName\";\n" +
	"\x12ListBackupsRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\"\x8e\x01\n" +
	"\n" +
	"BackupInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12&\n" +
	"\x0fcreated_at_unix\x18\x04 \x01(\x03R\rcreatedAtUnix\"D\n" +
	"\x13ListBackupsResponse\x12-\n" +
	"\abackups\x18\x01 \x03(\v2\x13.wgagent.BackupInfoR\abackups\"<\n" +
	"\x13CreateBackupRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\"s\n" +
	"\x14CreateBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12+\n" +
	"\x06backup\x18\x03 \x01(\v2\x13.wgagent.BackupInfoR\x06backup\"&\n" +
	"\x10GetBackupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"!\n" +
	"\vBackupChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"Q\n" +
	"\x14RestoreBackupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\"G\n" +
	"\x15RestoreBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\x13DeleteBackupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"F\n" +
	"\x14DeleteBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x18\n" +
	"\x16GetBypassConfigRequest\"\xaa\x01\n" +
	"\x17GetBypassConfigResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12(\n" +
	"\x10modified_at_unix\x18\x04 \x01(\x03R\x0emodifiedAtUnix\x12\x1d\n" +
	"\n" +
	"ipset_name\x18\x05 \x01(\tR\tipsetName\"Z\n" +
	"\x19UpdateBypassConfigRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12#\n" +
	"\rcreate_backup\x18\x02 \x01(\bR\fcreateBackup\"s\n" +
	"\x1aUpdateBypassConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x0erestart_output\x18\x03 \x01(\tR\rrestartOutput\"\x19\n" +
	"\x17ClearBypassIpsetRequest\"\x94\x01\n" +
	"\x18ClearBypassIpsetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\fflush_output\x18\x03 \x01(\tR\vflushOutput\x12%\n" +
	"\x0erestart_output\x18\x04 \x01(\tR\rrestartOutput2\xd4\t\n" +
	"\aWGAgent\x129\n" +
	"\x06Health\x12\x16.wgagent.HealthRequest\x1a\x17.wgagent.HealthResponse\x123\n" +
	"\x04Show\x12\x14.wgagent.ShowRequest\x1a\x15.wgagent.ShowResponse\x12?\n" +
	"\bSyncConf\x12\x18.wgagent.SyncConfRequest\x1a\x19.wgagent.SyncConfResponse\x12<\n" +
	"\aSetPeer\x12\x17.wgagent.SetPeerRequest\x1a\x18.wgagent.SetPeerResponse\x12E\n" +
	"\n" +
	"RemovePeer\x12\x1a.wgagent.RemovePeerRequest\x1a\x1b.wgagent.RemovePeerResponse\x129\n" +
	"\x06GenPSK\x12\x16.wgagent.GenPSKRequest\x1a\x17.wgagent.GenPSKResponse\x12E\n" +
	"\n" +
	"GenKeyPair\x12\x1a.wgagent.GenKeyPairRequest\x1a\x1b.wgagent.GenKeyPairResponse\x12E\n" +
	"\n" +
	"ReadConfig\x12\x1a.wgagent.ReadConfigRequest\x1a\x1b.wgagent.ReadConfigResponse\x12H\n" +
	"\vWriteConfig\x12\x1b.wgagent.WriteConfigRequest\x1a\x1c.wgagent.WriteConfigResponse\x12H\n" +
	"\vListBackups\x12\x1b.wgagent.ListBackupsRequest\x1a\x1c.wgagent.ListBackupsResponse\x12K\n" +
	"\fCreateBackup\x12\x1c.wgagent.CreateBackupRequest\x1a\x1d.wgagent.CreateBackupResponse\x12>\n" +
	"\tGetBackup\x12\x19.wgagent.GetBackupRequest\x1a\x14.wgagent.BackupChunk0\x01\x12N\n" +
	"\rRestoreBackup\x12\x1d.wgagent.RestoreBackupRequest\x1a\x1e.wgagent.RestoreBackupResponse\x12K\n" +
	"\fDeleteBackup\x12\x1c.wgagent.DeleteBackupRequest\x1a\x1d.wgagent.DeleteBackupResponse\x12T\n" +
	"\x0fGetBypassConfig\x12\x1f.wgagent.GetBypassConfigRequest\x1a .wgagent.GetBypassConfigResponse\x12]\n" +
	"\x12UpdateBypassConfig\x12\".wgagent.UpdateBypassConfigRequest\x1a#.wgagent.UpdateBypassConfigResponse\x12W\n" +
	"\x10ClearBypassIpset\x12 .wgagent.ClearBypassIpsetRequest\x1a!.wgagent.ClearBypassIpsetResponseB\x14Z\x12wg-agent/api/protob\x06proto3"

var (
	file_api_proto_agent_proto_rawDescOnce sync.Once
	file_api_proto_agent_proto_rawDescData []byte
)

func file_api_proto_agent_proto_rawDescGZIP() []byte {
	file_api_proto_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)))
	})
	return file_api_proto_agent_proto_rawDescData
}

var file_api_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_api_proto_agent_proto_goTypes = []any{
	(*HealthRequest)(nil),              // 0: wgagent.HealthRequest
	(*HealthResponse)(nil),             // 1: wgagent.HealthResponse
	(*ShowRequest)(nil),                // 2: wgagent.ShowRequest
	(*ShowResponse)(nil),               // 3: wgagent.ShowResponse
	(*PeerStatus)(nil),                 // 4: wgagent.PeerStatus
	(*SyncConfRequest)(nil),            // 5: wgagent.SyncConfRequest
	(*SyncConfResponse)(nil),           // 6: wgagent.SyncConfResponse
	(*SetPeerRequest)(nil),             // 7: wgagent.SetPeerRequest
	(*SetPeerResponse)(nil),            // 8: wgagent.SetPeerResponse
	(*RemovePeerRequest)(nil),          // 9: wgagent.RemovePeerRequest
	(*RemovePeerResponse)(nil),         // 10: wgagent.RemovePeerResponse
	(*GenPSKRequest)(nil),              // 11: wgagent.GenPSKRequest
	(*GenPSKResponse)(nil),             // 12: wgagent.GenPSKResponse
	(*GenKeyPairRequest)(nil),          // 13: wgagent.GenKeyPairRequest
	(*GenKeyPairResponse)(nil),         // 14: wgagent.GenKeyPairResponse
	(*ReadConfigRequest)(nil),          // 15: wgagent.ReadConfigRequest
	(*ReadConfigResponse)(nil),         // 16: wgagent.ReadConfigResponse
	(*WriteConfigRequest)(nil),         // 17: wgagent.WriteConfigRequest
	(*WriteConfigResponse)(nil),        // 18: wgagent.WriteConfigResponse
	(*ListBackupsRequest)(nil),         // 19: wgagent.ListBackupsRequest
	(*BackupInfo)(nil),                 // 20: wgagent.BackupInfo
	(*ListBackupsResponse)(nil),        // 21: wgagent.ListBackupsResponse
	(*CreateBackupRequest)(nil),        // 22: wgagent.CreateBackupRequest
	(*CreateBackupResponse)(nil),       // 23: wgagent.CreateBackupResponse
	(*GetBackupRequest)(nil),           // 24: wgagent.GetBackupRequest
	(*BackupChunk)(nil),                // 25: wgagent.BackupChunk
	(*RestoreBackupRequest)(nil),       // 26: wgagent.RestoreBackupRequest
	(*RestoreBackupResponse)(nil),      // 27: wgagent.RestoreBackupResponse
	(*DeleteBackupRequest)(nil),        // 28: wgagent.DeleteBackupRequest
	(*DeleteBackupResponse)(nil),       // 29: wgagent.DeleteBackupResponse
	(*GetBypassConfigRequest)(nil),     // 30: wgagent.GetBypassConfigRequest
	(*GetBypassConfigResponse)(nil),    // 31: wgagent.GetBypassConfigResponse
	(*UpdateBypassConfigRequest)(nil),  // 32: wgagent.UpdateBypassConfigRequest
	(*UpdateBypassConfigResponse)(nil), // 33: wgagent.UpdateBypassConfigResponse
	(*ClearBypassIpsetRequest)(nil),    // 34: wgagent.ClearBypassIpsetRequest
	(*ClearBypassIpsetResponse)(nil),   // 35: wgagent.ClearBypassIpsetResponse
}
var file_api_proto_agent_proto_depIdxs = []int32{
	4,  // 0: wgagent.ShowResponse.peers:type_name -> wgagent.PeerStatus
	20, // 1: wgagent.ListBackupsResponse.backups:type_name -> wgagent.BackupInfo
	20, // 2: wgagent.CreateBackupResponse.backup:type_name -> wgagent.BackupInfo
	0,  // 3: wgagent.WGAgent.Health:input_type -> wgagent.HealthRequest
	2,  // 4: wgagent.WGAgent.Show:input_type -> wgagent.ShowRequest
	5,  // 5: wgagent.WGAgent.SyncConf:input_type -> wgagent.SyncConfRequest
	7,  // 6: wgagent.WGAgent.SetPeer:input_type -> wgagent.SetPeerRequest
	9,  // 7: wgagent.WGAgent.RemovePeer:input_type -> wgagent.RemovePeerRequest
	11, // 8: wgagent.WGAgent.GenPSK:input_type -> wgagent.GenPSKRequest
	13, // 9: wgagent.WGAgent.GenKeyPair:input_type -> wgagent.GenKeyPairRequest
	15, // 10: wgagent.WGAgent.ReadConfig:input_type -> wgagent.ReadConfigRequest
	17, // 11: wgagent.WGAgent.WriteConfig:input_type -> wgagent.WriteConfigRequest
	19, // 12: wgagent.WGAgent.ListBackups:input_type -> wgagent.ListBackupsRequest
	22, // 13: wgagent.WGAgent.CreateBackup:input_type -> wgagent.CreateBackupRequest
	24, // 14: wgagent.WGAgent.GetBackup:input_type -> wgagent.GetBackupRequest
	26, // 15: wgagent.WGAgent.RestoreBackup:input_type -> wgagent.RestoreBackupRequest
	28, // 16: wgagent.WGAgent.DeleteBackup:input_type -> wgagent.DeleteBackupRequest
	30, // 17: wgagent.WGAgent.GetBypassConfig:input_type -> wgagent.GetBypassConfigRequest
	32, // 18: wgagent.WGAgent.UpdateBypassConfig:input_type -> wgagent.UpdateBypassConfigRequest
	34, // 19: wgagent.WGAgent.ClearBypassIpset:input_type -> wgagent.ClearBypassIpsetRequest
	1,  // 20: wgagent.WGAgent.Health:output_type -> wgagent.HealthResponse
	3,  // 21: wgagent.WGAgent.Show:output_type -> wgagent.ShowResponse
	6,  // 22: wgagent.WGAgent.SyncConf:output_type -> wgagent.SyncConfResponse
	8,  // 23: wgagent.WGAgent.SetPeer:output_type -> wgagent.SetPeerResponse
	10, // 24: wgagent.WGAgent.RemovePeer:output_type -> wgagent.RemovePeerResponse
	12, // 25: wgagent.WGAgent.GenPSK:output_type -> wgagent.GenPSKResponse
	14, // 26: wgagent.WGAgent.GenKeyPair:output_type -> wgagent.GenKeyPairResponse
	16, // 27: wgagent.WGAgent.ReadConfig:output_type -> wgagent.ReadConfigResponse
	18, // 28: wgagent.WGAgent.WriteConfig:output_type -> wgagent.WriteConfigResponse
	21, // 29: wgagent.WGAgent.ListBackups:output_type -> wgagent.ListBackupsResponse
	23, // 30: wgagent.WGAgent.CreateBackup:output_type -> wgagent.CreateBackupResponse
	25, // 31: wgagent.WGAgent.GetBackup:output_type -> wgagent.BackupChunk
	27, // 32: wgagent.WGAgent.RestoreBackup:output_type -> wgagent.RestoreBackupResponse
	29, // 33: wgagent.WGAgent.DeleteBackup:output_type -> wgagent.DeleteBackupResponse
	31, // 34: wgagent.WGAgent.GetBypassConfig:output_type -> wgagent.GetBypassConfigResponse
	33, // 35: wgagent.WGAgent.UpdateBypassConfig:output_type -> wgagent.UpdateBypassConfigResponse
	35, // 36: wgagent.WGAgent.ClearBypassIpset:output_type -> wgagent.ClearBypassIpsetResponse
	20, // [20:37] is the sub-list for method output_type
	3,  // [3:20] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_agent_proto_init() }
func file_api_proto_agent_proto_init() {
	if File_api_proto_agent_proto != nil {
		return
	}
	file_api_proto_agent_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_proto_msgTypes,
	}.Build()
	File_api_proto_agent_proto = out.File
	file_api_proto_agent_proto_goTypes = nil
	file_api_proto_agent_proto_depIdxs = nil
}
