// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/agent.proto

package wgagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WGAgent_Health_FullMethodName        = "/wgagent.WGAgent/Health"
	WGAgent_Show_FullMethodName          = "/wgagent.WGAgent/Show"
	WGAgent_SyncConf_FullMethodName      = "/wgagent.WGAgent/SyncConf"
	WGAgent_SetPeer_FullMethodName       = "/wgagent.WGAgent/SetPeer"
	WGAgent_RemovePeer_FullMethodName    = "/wgagent.WGAgent/RemovePeer"
	WGAgent_GenPSK_FullMethodName        = "/wgagent.WGAgent/GenPSK"
	WGAgent_GenKeyPair_FullMethodName    = "/wgagent.WGAgent/GenKeyPair"
	WGAgent_ReadConfig_FullMethodName    = "/wgagent.WGAgent/ReadConfig"
	WGAgent_WriteConfig_FullMethodName   = "/wgagent.WGAgent/WriteConfig"
	WGAgent_ListBackups_FullMethodName   = "/wgagent.WGAgent/ListBackups"
	WGAgent_CreateBackup_FullMethodName  = "/wgagent.WGAgent/CreateBackup"
	WGAgent_GetBackup_FullMethodName     = "/wgagent.WGAgent/GetBackup"
	WGAgent_RestoreBackup_FullMethodName = "/wgagent.WGAgent/RestoreBackup"
	WGAgent_DeleteBackup_FullMethodName  = "/wgagent.WGAgent/DeleteBackup"
)

// WGAgentClient is the client API for WGAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WGAgent is the service that runs on each WireGuard server.
// It provides remote execution of WireGuard operations via gRPC with mTLS.
type WGAgentClient interface {
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// WireGuard operations
	Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error)
	SyncConf(ctx context.Context, in *SyncConfRequest, opts ...grpc.CallOption) (*SyncConfResponse, error)
	SetPeer(ctx context.Context, in *SetPeerRequest, opts ...grpc.CallOption) (*SetPeerResponse, error)
	RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error)
	GenPSK(ctx context.Context, in *GenPSKRequest, opts ...grpc.CallOption) (*GenPSKResponse, error)
	GenKeyPair(ctx context.Context, in *GenKeyPairRequest, opts ...grpc.CallOption) (*GenKeyPairResponse, error)
	// Config file operations
	ReadConfig(ctx context.Context, in *ReadConfigRequest, opts ...grpc.CallOption) (*ReadConfigResponse, error)
	WriteConfig(ctx context.Context, in *WriteConfigRequest, opts ...grpc.CallOption) (*WriteConfigResponse, error)
	// Backup operations
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error)
	GetBackup(ctx context.Context, in *GetBackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupChunk], error)
	RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error)
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error)
}

type wGAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewWGAgentClient(cc grpc.ClientConnInterface) WGAgentClient {
	return &wGAgentClient{cc}
}

func (c *wGAgentClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, WGAgent_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowResponse)
	err := c.cc.Invoke(ctx, WGAgent_Show_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) SyncConf(ctx context.Context, in *SyncConfRequest, opts ...grpc.CallOption) (*SyncConfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncConfResponse)
	err := c.cc.Invoke(ctx, WGAgent_SyncConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) SetPeer(ctx context.Context, in *SetPeerRequest, opts ...grpc.CallOption) (*SetPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPeerResponse)
	err := c.cc.Invoke(ctx, WGAgent_SetPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePeerResponse)
	err := c.cc.Invoke(ctx, WGAgent_RemovePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) GenPSK(ctx context.Context, in *GenPSKRequest, opts ...grpc.CallOption) (*GenPSKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenPSKResponse)
	err := c.cc.Invoke(ctx, WGAgent_GenPSK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) GenKeyPair(ctx context.Context, in *GenKeyPairRequest, opts ...grpc.CallOption) (*GenKeyPairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenKeyPairResponse)
	err := c.cc.Invoke(ctx, WGAgent_GenKeyPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) ReadConfig(ctx context.Context, in *ReadConfigRequest, opts ...grpc.CallOption) (*ReadConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadConfigResponse)
	err := c.cc.Invoke(ctx, WGAgent_ReadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) WriteConfig(ctx context.Context, in *WriteConfigRequest, opts ...grpc.CallOption) (*WriteConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteConfigResponse)
	err := c.cc.Invoke(ctx, WGAgent_WriteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupsResponse)
	err := c.cc.Invoke(ctx, WGAgent_ListBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBackupResponse)
	err := c.cc.Invoke(ctx, WGAgent_CreateBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) GetBackup(ctx context.Context, in *GetBackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WGAgent_ServiceDesc.Streams[0], WGAgent_GetBackup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBackupRequest, BackupChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WGAgent_GetBackupClient = grpc.ServerStreamingClient[BackupChunk]

func (c *wGAgentClient) RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreBackupResponse)
	err := c.cc.Invoke(ctx, WGAgent_RestoreBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wGAgentClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBackupResponse)
	err := c.cc.Invoke(ctx, WGAgent_DeleteBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WGAgentServer is the server API for WGAgent service.
// All implementations must embed UnimplementedWGAgentServer
// for forward compatibility.
//
// WGAgent is the service that runs on each WireGuard server.
// It provides remote execution of WireGuard operations via gRPC with mTLS.
type WGAgentServer interface {
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// WireGuard operations
	Show(context.Context, *ShowRequest) (*ShowResponse, error)
	SyncConf(context.Context, *SyncConfRequest) (*SyncConfResponse, error)
	SetPeer(context.Context, *SetPeerRequest) (*SetPeerResponse, error)
	RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error)
	GenPSK(context.Context, *GenPSKRequest) (*GenPSKResponse, error)
	GenKeyPair(context.Context, *GenKeyPairRequest) (*GenKeyPairResponse, error)
	// Config file operations
	ReadConfig(context.Context, *ReadConfigRequest) (*ReadConfigResponse, error)
	WriteConfig(context.Context, *WriteConfigRequest) (*WriteConfigResponse, error)
	// Backup operations
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error)
	CreateBackup(context.Context, *CreateBackupRequest) (*CreateBackupResponse, error)
	GetBackup(*GetBackupRequest, grpc.ServerStreamingServer[BackupChunk]) error
	RestoreBackup(context.Context, *RestoreBackupRequest) (*RestoreBackupResponse, error)
	DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error)
	mustEmbedUnimplementedWGAgentServer()
}

// UnimplementedWGAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWGAgentServer struct{}

func (UnimplementedWGAgentServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedWGAgentServer) Show(context.Context, *ShowRequest) (*ShowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Show not implemented")
}
func (UnimplementedWGAgentServer) SyncConf(context.Context, *SyncConfRequest) (*SyncConfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncConf not implemented")
}
func (UnimplementedWGAgentServer) SetPeer(context.Context, *SetPeerRequest) (*SetPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPeer not implemented")
}
func (UnimplementedWGAgentServer) RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePeer not implemented")
}
func (UnimplementedWGAgentServer) GenPSK(context.Context, *GenPSKRequest) (*GenPSKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenPSK not implemented")
}
func (UnimplementedWGAgentServer) GenKeyPair(context.Context, *GenKeyPairRequest) (*GenKeyPairResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenKeyPair not implemented")
}
func (UnimplementedWGAgentServer) ReadConfig(context.Context, *ReadConfigRequest) (*ReadConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadConfig not implemented")
}
func (UnimplementedWGAgentServer) WriteConfig(context.Context, *WriteConfigRequest) (*WriteConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteConfig not implemented")
}
func (UnimplementedWGAgentServer) ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackups not implemented")
}
func (UnimplementedWGAgentServer) CreateBackup(context.Context, *CreateBackupRequest) (*CreateBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBackup not implemented")
}
func (UnimplementedWGAgentServer) GetBackup(*GetBackupRequest, grpc.ServerStreamingServer[BackupChunk]) error {
	return status.Error(codes.Unimplemented, "method GetBackup not implemented")
}
func (UnimplementedWGAgentServer) RestoreBackup(context.Context, *RestoreBackupRequest) (*RestoreBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreBackup not implemented")
}
func (UnimplementedWGAgentServer) DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (UnimplementedWGAgentServer) mustEmbedUnimplementedWGAgentServer() {}
func (UnimplementedWGAgentServer) testEmbeddedByValue()                 {}

// UnsafeWGAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WGAgentServer will
// result in compilation errors.
type UnsafeWGAgentServer interface {
	mustEmbedUnimplementedWGAgentServer()
}

func RegisterWGAgentServer(s grpc.ServiceRegistrar, srv WGAgentServer) {
	// If the following call panics, it indicates UnimplementedWGAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WGAgent_ServiceDesc, srv)
}

func _WGAgent_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_Show_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).Show(ctx, req.(*ShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_SyncConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).SyncConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_SyncConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).SyncConf(ctx, req.(*SyncConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_SetPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).SetPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_SetPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).SetPeer(ctx, req.(*SetPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_RemovePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).RemovePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_RemovePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).RemovePeer(ctx, req.(*RemovePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_GenPSK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenPSKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).GenPSK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_GenPSK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).GenPSK(ctx, req.(*GenPSKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_GenKeyPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenKeyPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).GenKeyPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_GenKeyPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).GenKeyPair(ctx, req.(*GenKeyPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_ReadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).ReadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_ReadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).ReadConfig(ctx, req.(*ReadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_WriteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).WriteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_WriteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).WriteConfig(ctx, req.(*WriteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_ListBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_CreateBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_GetBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBackupRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WGAgentServer).GetBackup(m, &grpc.GenericServerStream[GetBackupRequest, BackupChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WGAgent_GetBackupServer = grpc.ServerStreamingServer[BackupChunk]

func _WGAgent_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_RestoreBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).RestoreBackup(ctx, req.(*RestoreBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WGAgent_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WGAgentServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WGAgent_DeleteBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WGAgentServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WGAgent_ServiceDesc is the grpc.ServiceDesc for WGAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WGAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wgagent.WGAgent",
	HandlerType: (*WGAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _WGAgent_Health_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _WGAgent_Show_Handler,
		},
		{
			MethodName: "SyncConf",
			Handler:    _WGAgent_SyncConf_Handler,
		},
		{
			MethodName: "SetPeer",
			Handler:    _WGAgent_SetPeer_Handler,
		},
		{
			MethodName: "RemovePeer",
			Handler:    _WGAgent_RemovePeer_Handler,
		},
		{
			MethodName: "GenPSK",
			Handler:    _WGAgent_GenPSK_Handler,
		},
		{
			MethodName: "GenKeyPair",
			Handler:    _WGAgent_GenKeyPair_Handler,
		},
		{
			MethodName: "ReadConfig",
			Handler:    _WGAgent_ReadConfig_Handler,
		},
		{
			MethodName: "WriteConfig",
			Handler:    _WGAgent_WriteConfig_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _WGAgent_ListBackups_Handler,
		},
		{
			MethodName: "CreateBackup",
			Handler:    _WGAgent_CreateBackup_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _WGAgent_RestoreBackup_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _WGAgent_DeleteBackup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBackup",
			Handler:       _WGAgent_GetBackup_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/agent.proto",
}
